skeletonapp/skeletonapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from generator.views import edit_skeleton

urlpatterns = [

    url(
        r'^edit/(?P<skid>[\d]+)$',
        edit_skeleton,
        name='skeleton_edit'
    ),
    url(r'^admin/', admin.site.urls),
]

skeletonapp/generator/models.py
from __future__ import unicode_literals

from django.db import models
from skeleton import parse, LoreParser, LorePredicate
import json

from django.core.urlresolvers import reverse

class SourceSentence(models.Model):
    """
    This represent individual sentence of the lore data
    """
    sentence = models.TextField()
    parsed = models.BooleanField(default=False)
    trips_parse = models.TextField(default="")
    word_map = models.TextField(default="")

    def __str__(self):
        return self.sentence

    def parse(self):
        """
        Try trips parse on the sentence
        """
        # If already parsed, simply return

        if self.parsed:
            return

        tparse, word_map = parse(self.sentence)
        self.trips_parse = json.dumps(tparse)
        self.word_map = json.dumps(word_map)

        self.parsed = True
        self.save()

    def get_trips_parse(self):
        if len(self.trips_parse) < 1:
            return None
        return json.loads(self.trips_parse)

    def get_word_map(self):
        if len(self.word_map) < 1:
            return None
        return json.loads(self.word_map)

    def get_predicate(self):
        a = LorePredicate("", "", self.sentence)
        a.parsed = self.get_trips_parse()
        a.role_dict = self.get_word_map()
        return a


class ProcessedSkeleton(models.Model):
    # Selected value of skeleton
    skeleton = models.TextField()

    sentence = models.ForeignKey(SourceSentence)
    # Save the exact skeleton extracted by trips
    trips_parse = models.TextField(default="")

    possible_entries = models.TextField(default="")
    surrounding_words = models.TextField(default="")

    TRIPS_GEN = 'a'
    MANUAL_SEL = 'b'
    SKELGEN_PROC = 'c'
    TYPE = (
        (TRIPS_GEN, 'TRIPS Generated'),
        (MANUAL_SEL, 'Manually Selected'),
        (SKELGEN_PROC, 'Processed by SkeletonGen'),
    )
    # How is the current skeleton processed?
    skeleton_type = models.CharField(
        max_length=1, choices=TYPE, default=TRIPS_GEN)

    def get_edit_url(self):
        if len(self.possible_entries) > 0:
            return '<a href="{}" target="_blank">Edit</a>'.format(
                reverse(
                    'skeleton_edit',
                    kwargs={"skid": self.pk}
                )
            )
        else:
            return 'N/A'
    get_edit_url.allow_tags = True

class Skeleton(models.Model):
    """
    This represent the final skeletons
    """
    skeleton = models.TextField()

skeletonapp/generator/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import ProcessedSkeleton
import json

def edit_skeleton(request, skid):
    """
    Edit the skeleton
    """

    template = loader.get_template('edit_skeleton.html')
    skeleton = get_object_or_404(ProcessedSkeleton, pk=skid)
    skeleton.pos_ent = json.loads(skeleton.possible_entries)
    current_head = skeleton.skeleton.split()[0][1:]
    after_head = " ".join(skeleton.skeleton.split()[1:])

    changed=False
    if request.method == 'POST':
        role = request.POST.get("role", None)
        if role in skeleton.possible_entries:
            skeleton.skeleton = "(" + role + " "+after_head
            skeleton.skeleton_type = ProcessedSkeleton.MANUAL_SEL
            skeleton.save()
            current_head = role
            changed=True

    context = {
        "skeleton": skeleton,
        "after_head": after_head,
        "current_head": current_head,
        "changed": changed,
    }

    return HttpResponse(template.render(context, request))

skeletonapp/templates/edit_skeleton.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Skeleton Generator</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/one-page-wonder.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Skeleton Generator</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
    </nav>

    <div class="container">
      <br/>
      {% if changed %}
      <div class="alert alert-success">
        <strong>Success!</strong> Role changed
      </div>
      {% endif %}
      <br/><br/>
      <b>Original Sentence</b>: {{ skeleton.sentence }} <br/>
      <b>Current Skeleton</b>: {{ skeleton.skeleton }} <br/>
      <b>TRIPS  output</b>: {{ skeleton.trips_parse }} <br/>
      <b>Possible Entries</b>: {{ skeleton.possible_entries }} <br/>
      <b>Type</b>: {{ skeleton.get_skeleton_type_display }} <br/>
      <h2>Select New Role</h2>
      <form action="" method="post">
        {% csrf_token %}
        ( <select name="role">
          {% for pe in skeleton.pos_ent %}
          {% if pe == current_head %}
          <option value="{{ pe }}" selected="selected">{{ pe }}</option>
          {% else %}
          <option value="{{ pe }}">{{ pe }}</option>
          {% endif %}
          {% endfor %}
        </select> {{ after_head }}

        <input type="submit" value="Change">
      </form>

      <hr class="featurette-divider">

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

  </body>

</html>